// AUTO-GENERATED by generate-game-asset.py. Do not hand-edit.
// Regenerate with: python3 generate-game-asset.py
export const gameHtml = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<title>Sudokuza - Classic Sudoku Puzzle</title>
<meta name="theme-color" content="#1e5940">
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="apple-mobile-web-app-title" content="Sudokuza">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,500;9..144,600&family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
<style>
  :root{
    --bg:#f0f2e9; --bg-deep:#1e5940; --bg-deep-2:#123c2a; --panel:#ffffff; --panel-2:#f2f0e6;
    --ink:#25302a; --ink-soft:#6a7568; --ink-on-deep:#f4f2e6; --ink-soft-on-deep:#a9bda6;
    --gold:#caa64a; --gold-ink:#2b2210; --moss:#4a8055; --berry:#b45447;
    --line:#e2ded0; --line-thick:#b3ab8c;
    --sel:#eae4c4; --peer:#f4f2e6; --same:#dceccf; --shadow:rgba(38,64,47,0.10);
    --display:'Fraunces',Georgia,serif; --body:'Inter',system-ui,sans-serif;
  }
  [data-mode="night"]{
    --bg:#0d0d0d; --bg-deep:#080808; --bg-deep-2:#040404; --panel:#161616; --panel-2:#1f1f1f;
    --ink:#ececec; --ink-soft:#9a9a9a; --ink-on-deep:#f2f2f2; --ink-soft-on-deep:#a8a8a8;
    --gold:#dcbb57; --gold-ink:#241d09; --moss:#72c583; --berry:#e08076;
    --line:#262626; --line-thick:#3c3c3c;
    --sel:#2e2e2e; --peer:#181818; --same:#26332a; --shadow:rgba(0,0,0,0.6);
  }
  *{box-sizing:border-box;}
  html,body{margin:0;min-height:100%;background:var(--bg);color:var(--ink);
    font-family:var(--body); transition:background .3s,color .3s;-webkit-font-smoothing:antialiased;}
  body{display:flex;justify-content:center;}
  .app{width:100%;max-width:460px;min-height:100vh;position:relative;overflow-x:hidden;}
  button{font-family:inherit;cursor:pointer;}
  .hidden{display:none !important;}
  h1,h2,h3{font-family:var(--display);font-weight:600;letter-spacing:-0.01em;}

  /* ---------- drawer ---------- */
  .drawer-toggle{position:fixed;top:14px;left:14px;z-index:40;width:42px;height:42px;border-radius:12px;
    border:none;background:var(--panel);color:var(--ink);box-shadow:0 2px 8px var(--shadow);
    display:flex;align-items:center;justify-content:center;padding:0;}
  .drawer-toggle span{display:block;width:18px;height:2px;background:var(--ink);position:relative;}
  .drawer-toggle span::before,.drawer-toggle span::after{content:"";position:absolute;left:0;width:18px;height:2px;background:var(--ink);}
  .drawer-toggle span::before{top:-6px;} .drawer-toggle span::after{top:6px;}
  .drawer-backdrop{position:fixed;inset:0;background:rgba(10,15,10,0.5);z-index:45;display:none;}
  .drawer-backdrop.show{display:block;}
  .drawer{position:fixed;top:0;left:0;bottom:0;width:82%;max-width:340px;background:var(--panel);
    z-index:46;transform:translateX(-100%);transition:transform .28s ease;padding:22px 18px;overflow-y:auto;
    box-shadow:4px 0 20px var(--shadow);}
  .drawer.open{transform:translateX(0);}
  .drawer h3{margin:18px 0 8px;font-size:1.02rem;}
  .drawer .close-drawer{background:none;border:none;font-size:1.3rem;color:var(--ink);float:right;}
  .companion-card{background:var(--panel-2);border-radius:18px;padding:16px;text-align:center;margin-top:6px;}
  .companion-emoji{font-size:2.6rem;}
  .companion-stage{font-weight:700;margin-top:4px;font-size:0.92rem;}
  .companion-sub{font-size:0.78rem;color:var(--ink-soft);margin-top:2px;}
  .drawer-row{display:flex;justify-content:space-between;align-items:center;background:var(--panel-2);
    border-radius:12px;padding:11px 14px;margin-bottom:8px;font-size:0.86rem;}
  .drawer-row .v{font-weight:700;}
  .toggle-switch{display:flex;background:var(--panel-2);border-radius:12px;padding:4px;margin-bottom:14px;}
  .color-swatch-row{display:flex;gap:10px;margin-bottom:14px;flex-wrap:wrap;}
  .color-swatch{width:38px;height:38px;border-radius:50%;border:3px solid transparent;cursor:pointer;
    position:relative;flex:0 0 auto;}
  .color-swatch.selected{border-color:var(--ink);}
  .color-swatch.selected::after{content:"✓";position:absolute;inset:0;display:flex;align-items:center;
    justify-content:center;color:#fff;font-size:0.85rem;font-weight:800;text-shadow:0 1px 2px rgba(0,0,0,0.4);}
  .toggle-switch button{flex:1;border:none;background:none;padding:9px 0;border-radius:9px;font-weight:600;
    font-size:0.84rem;color:var(--ink-soft);}
  .toggle-switch button.active{background:var(--gold);color:var(--gold-ink);}
  .usp-item{display:flex;gap:10px;margin-bottom:12px;font-size:0.83rem;line-height:1.4;color:var(--ink-soft);}
  .usp-item .uicon{font-size:1.1rem;}
  .drawer-btn{width:100%;background:var(--bg-deep);color:var(--ink-on-deep);border:none;border-radius:12px;
    padding:12px;font-weight:600;margin-bottom:8px;font-size:0.88rem;}

  /* ---------- HOME ---------- */
  .hero{background:linear-gradient(158deg,var(--bg-deep),var(--bg-deep-2));color:var(--ink-on-deep);
    padding:64px 22px 42px;position:relative;}
  .hero[data-pattern="dots"]{background-image:radial-gradient(rgba(255,255,255,0.09) 1.5px,transparent 1.5px),linear-gradient(158deg,var(--bg-deep),var(--bg-deep-2));background-size:16px 16px,auto;}
  .hero[data-pattern="petals"]{background-image:radial-gradient(rgba(255,255,255,0.11) 2.2px,transparent 2.2px),linear-gradient(158deg,var(--bg-deep),var(--bg-deep-2));background-size:22px 22px,auto;}
  .hero[data-pattern="waves"]{background-image:repeating-linear-gradient(115deg,rgba(255,255,255,0.07) 0 2px,transparent 2px 16px),linear-gradient(158deg,var(--bg-deep),var(--bg-deep-2));}
  .hero[data-pattern="sparks"]{background-image:radial-gradient(rgba(255,255,255,0.13) 1.5px,transparent 1.5px),linear-gradient(158deg,var(--bg-deep),var(--bg-deep-2));background-size:11px 11px;}
  .hero h1{font-size:2rem;margin:0 0 2px;}
  .hero .tag{font-size:0.82rem;color:var(--ink-soft-on-deep);margin:0;}
  .coin-strip{position:absolute;top:16px;right:18px;display:flex;gap:8px;}
  .coin-pill{background:rgba(255,255,255,0.10);border-radius:20px;padding:5px 11px;font-size:0.78rem;
    font-weight:700;display:inline-flex;align-items:center;gap:5px;}
  .pill-ico{width:15px;height:15px;display:block;flex:0 0 auto;}

  /* level card (now up top) */
  .level-card{margin:24px 20px 0;background:var(--panel);border-radius:18px;padding:18px;
    box-shadow:0 3px 14px var(--shadow);}
  .level-card .lc-head{display:flex;justify-content:space-between;align-items:baseline;margin-bottom:3px;}
  .level-card .lc-region{font-family:var(--display);font-size:1.15rem;}
  .level-card .lc-num{font-size:0.78rem;color:var(--ink-soft);font-weight:600;}
  .level-card .lc-sub{font-size:0.78rem;color:var(--ink-soft);margin-bottom:14px;}
  .level-strip{display:flex;gap:7px;margin-bottom:16px;}
  .level-strip .lvchip{flex:1;aspect-ratio:1/1;border-radius:12px;display:flex;align-items:center;
    justify-content:center;font-weight:700;font-size:0.9rem;background:var(--panel-2);color:var(--ink-soft);
    border:2px solid transparent;position:relative;}
  .level-strip .lvchip.done{background:var(--same);color:var(--moss);}
  .level-strip .lvchip.active{background:var(--gold);color:var(--gold-ink);border-color:var(--gold);
    box-shadow:0 3px 10px rgba(202,166,74,0.35);transform:scale(1.06);}
  .level-strip .lvchip.locked{opacity:0.45;}
  .level-strip .lvchip .lock{font-size:0.7rem;}
  .cta-btn{width:100%;background:var(--bg-deep);color:var(--ink-on-deep);border:none;border-radius:13px;
    padding:15px;font-weight:700;font-size:0.98rem;box-shadow:0 4px 14px var(--shadow);}

  .section{padding:0 20px;margin-top:14px;}
  .section-label{font-family:var(--display);font-size:1.05rem;margin:24px 0 10px;}

  .diff-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;}
  .diff-tile{display:flex;flex-direction:column;align-items:flex-start;gap:2px;border:none;border-radius:14px;
    padding:16px 16px;box-shadow:0 3px 14px var(--shadow);text-align:left;color:#fff;}
  .diff-tile .dt-name{font-family:var(--display);font-size:1.05rem;font-weight:600;}
  .diff-tile .dt-sub{font-size:0.72rem;opacity:0.9;}
  .diff-tile:active{transform:scale(0.98);}
  .d-easy{background:linear-gradient(135deg,#5bab6e,#3f8a55);}
  .d-medium{background:linear-gradient(135deg,#4a95c4,#357aa8);}
  .d-hard{background:linear-gradient(135deg,#c98a3f,#a86a28);}
  .d-expert{background:linear-gradient(135deg,#9a5bb0,#7a3f95);}

  /* daily (now below level) */
  .daily-card{background:var(--panel);border-radius:16px;padding:16px;box-shadow:0 3px 14px var(--shadow);}
  .daily-card .dtitle{font-weight:700;font-size:0.92rem;margin-bottom:2px;display:flex;align-items:center;gap:6px;}
  .daily-card .dsub{font-size:0.76rem;color:var(--ink-soft);margin-bottom:12px;}
  .daily-btn{width:100%;border:none;border-radius:11px;padding:12px;font-weight:700;font-size:0.88rem;
    background:var(--gold);color:var(--gold-ink);}
  .daily-done{font-size:0.8rem;font-weight:600;color:var(--moss);}

  /* reward preview on home */
  .reward-preview{background:var(--panel);border-radius:16px;padding:16px;box-shadow:0 3px 14px var(--shadow);}
  .reward-preview .rp-top{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px;}
  .reward-preview .rp-title{font-weight:700;font-size:0.95rem;}
  .reward-preview .rp-open{background:var(--panel-2);border:none;border-radius:9px;padding:7px 12px;
    font-weight:700;font-size:0.76rem;color:var(--ink);}
  .chest-bar-wrap{margin-bottom:12px;}
  .chest-bar-label{display:flex;justify-content:space-between;font-size:0.72rem;color:var(--ink-soft);margin-bottom:5px;}
  .chest-bar{height:10px;background:var(--panel-2);border-radius:6px;overflow:hidden;}
  .chest-bar .fill{height:100%;background:linear-gradient(90deg,var(--gold),var(--moss));border-radius:6px;
    transition:width .4s ease;}
  .garden-mini{display:grid;grid-template-columns:repeat(6,1fr);gap:6px;}
  .garden-mini .plot{aspect-ratio:1/1;border-radius:9px;background:var(--panel-2);display:flex;
    align-items:center;justify-content:center;font-size:1.1rem;}
  .garden-mini .plot.grown{background:var(--same);}
  .garden-mini .plot.empty{opacity:0.4;font-size:0.7rem;color:var(--ink-soft);}

  .usp-strip{display:flex;flex-direction:column;gap:9px;margin-top:12px;padding-bottom:40px;}
  .usp-mini{display:flex;gap:10px;align-items:flex-start;background:var(--panel-2);border-radius:12px;
    padding:12px 14px;}
  .usp-mini .mi{font-size:1.1rem;}
  .usp-mini .mt{font-size:0.77rem;line-height:1.35;color:var(--ink-soft);}
  .usp-mini .mt b{color:var(--ink);font-weight:700;}

  /* ---------- GAME ---------- */
  #gameScreen{padding:0 16px 30px;}
  .gtopbar{display:flex;align-items:center;justify-content:space-between;
    margin:0 -16px 16px;padding:60px 16px 16px;
    background:linear-gradient(158deg,var(--bg-deep),var(--bg-deep-2));
    border-radius:0 0 22px 22px;position:relative;}
  .gtopbar[data-pattern="dots"]{background-image:radial-gradient(rgba(255,255,255,0.09) 1.5px,transparent 1.5px),linear-gradient(158deg,var(--bg-deep),var(--bg-deep-2));background-size:16px 16px,auto;}
  .gtopbar[data-pattern="petals"]{background-image:radial-gradient(rgba(255,255,255,0.11) 2.2px,transparent 2.2px),linear-gradient(158deg,var(--bg-deep),var(--bg-deep-2));background-size:22px 22px,auto;}
  .gtopbar[data-pattern="waves"]{background-image:repeating-linear-gradient(115deg,rgba(255,255,255,0.07) 0 2px,transparent 2px 16px),linear-gradient(158deg,var(--bg-deep),var(--bg-deep-2));}
  .gtopbar[data-pattern="sparks"]{background-image:radial-gradient(rgba(255,255,255,0.13) 1.5px,transparent 1.5px),linear-gradient(158deg,var(--bg-deep),var(--bg-deep-2));background-size:11px 11px;}
  .gtopbar .region-tag{font-family:var(--display);font-size:0.98rem;color:var(--ink-on-deep);}
  .gtopbar .icon-btn{width:36px;height:36px;border-radius:11px;border:none;background:rgba(255,255,255,0.14);
    color:var(--ink-on-deep);font-size:15px;display:flex;align-items:center;justify-content:center;box-shadow:none;}
  .statrow{display:flex;justify-content:space-between;background:var(--panel);border-radius:13px;
    padding:10px 6px;margin-bottom:10px;box-shadow:0 1px 3px var(--shadow);}
  .stat{text-align:center;flex:1;}
  .stat .label{font-size:0.56rem;color:var(--ink-soft);text-transform:uppercase;letter-spacing:.04em;font-weight:600;}
  .stat .value{font-weight:800;font-size:0.98rem;margin-top:2px;}
  .stat .value.danger{color:var(--berry);}
  .board-shell{position:relative;background:var(--panel);border-radius:16px;padding:8px;box-shadow:0 3px 14px var(--shadow);}
  .board{display:grid;grid-template-columns:repeat(9,1fr);grid-template-rows:repeat(9,1fr);
    width:100%;aspect-ratio:1/1;border:2px solid var(--line-thick);border-radius:8px;overflow:hidden;}
  .cell{position:relative;display:flex;align-items:center;justify-content:center;font-size:1.15rem;
    font-weight:600;cursor:pointer;background:var(--panel);color:var(--ink);user-select:none;font-family:var(--body);}
  .cell.entry{color:var(--moss);font-weight:700;}
  .cell.error{color:var(--berry);font-weight:700;}
  .cell.peer{background:var(--peer);}
  .cell.same{background:var(--same);}
  .cell.selected{background:var(--sel);}
  .cell .notes{position:absolute;inset:2px;display:grid;grid-template-columns:repeat(3,1fr);grid-template-rows:repeat(3,1fr);}
  .cell .notes span{font-size:0.5rem;font-weight:500;color:var(--ink-soft);display:flex;align-items:center;justify-content:center;}
  .coach-panel{background:var(--panel-2);border-radius:12px;padding:12px 14px;margin-top:10px;
    font-size:0.82rem;display:none;gap:8px;align-items:flex-start;line-height:1.4;}
  .coach-panel.show{display:flex;}
  .coach-panel .ci{font-size:1.2rem;}
  .toolbar{display:flex;justify-content:space-around;margin:12px 0 8px;}
  .tool{background:none;border:none;display:flex;flex-direction:column;align-items:center;gap:4px;
    color:var(--ink-soft);font-size:0.64rem;cursor:pointer;position:relative;font-weight:600;}
  .tool .ticon{width:42px;height:42px;border-radius:13px;background:var(--panel);display:flex;
    align-items:center;justify-content:center;font-size:1.05rem;color:var(--ink);box-shadow:0 1px 3px var(--shadow);}
  .tool.active .ticon{background:var(--gold);color:var(--gold-ink);}
  .tool .badge{position:absolute;top:-4px;right:2px;background:var(--gold);color:var(--gold-ink);
    font-size:0.56rem;font-weight:800;border-radius:8px;padding:1px 5px;}
  .numpad{display:grid;grid-template-columns:repeat(9,1fr);gap:6px;}
  .numbtn{background:var(--panel);border:none;border-radius:11px;padding:12px 0;font-size:1.05rem;
    font-weight:700;color:var(--moss);cursor:pointer;box-shadow:0 1px 3px var(--shadow);}
  .numbtn:disabled{color:var(--line-thick);cursor:default;box-shadow:none;}

  /* ---------- overlays ---------- */
  .overlay{position:fixed;inset:0;background:rgba(10,15,10,0.55);display:none;align-items:center;
    justify-content:center;z-index:50;padding:20px;}
  .overlay.show{display:flex;}
  .modal{background:var(--panel);border-radius:18px;padding:22px;max-width:390px;width:100%;
    max-height:84vh;overflow-y:auto;color:var(--ink);}
  .modal h2{margin:0 0 4px;font-size:1.3rem;}
  .modal p.sub{margin:0 0 16px;color:var(--ink-soft);font-size:0.82rem;}
  .modal-close{float:right;background:var(--panel-2);border:none;border-radius:9px;width:30px;height:30px;
    cursor:pointer;font-size:1rem;color:var(--ink);}
  .diff-option{display:flex;justify-content:space-between;align-items:center;background:var(--panel-2);
    border-radius:11px;padding:12px 16px;margin-bottom:8px;cursor:pointer;font-weight:600;}
  .diff-option small{display:block;font-weight:400;color:var(--ink-soft);font-size:0.74rem;margin-top:2px;}
  .stat-row{display:flex;justify-content:space-between;align-items:center;background:var(--panel-2);
    border-radius:11px;padding:12px 14px;margin-bottom:8px;}
  .stat-row .srlabel{font-size:0.84rem;color:var(--ink-soft);}
  .stat-row .srvalue{font-weight:800;font-size:1.0rem;}
  .badge-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;}
  .badge-item{background:var(--panel-2);border-radius:12px;padding:12px 6px;text-align:center;}
  .badge-item.locked{opacity:0.32;}
  .badge-item .bicon{font-size:1.45rem;}
  .badge-item .bname{font-size:0.58rem;font-weight:600;margin-top:4px;}

  /* reward center tabs */
  .rc-tabs{display:flex;background:var(--panel-2);border-radius:12px;padding:4px;margin-bottom:14px;}
  .rc-tabs button{flex:1;border:none;background:none;padding:9px 0;border-radius:9px;font-weight:700;
    font-size:0.8rem;color:var(--ink-soft);}
  .rc-tabs button.active{background:var(--panel);color:var(--ink);box-shadow:0 1px 3px var(--shadow);}
  .rc-balance{display:flex;gap:8px;margin-bottom:14px;}
  .rc-balance .bpill{flex:1;background:var(--panel-2);border-radius:12px;padding:10px;text-align:center;}
  .rc-balance .bpill .bv{font-weight:800;font-size:1.05rem;}
  .rc-balance .bpill .bl{font-size:0.66rem;color:var(--ink-soft);}
  .garden-full{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;}
  .gplot{background:var(--panel-2);border-radius:12px;padding:12px 6px;text-align:center;}
  .gplot .gp-emoji{font-size:1.7rem;}
  .gplot .gp-name{font-size:0.62rem;font-weight:600;margin:4px 0;}
  .gplot .gp-btn{border:none;border-radius:8px;padding:5px 8px;font-size:0.66rem;font-weight:700;
    background:var(--moss);color:#fff;width:100%;}
  .gplot .gp-btn:disabled{background:var(--line);color:var(--ink-soft);}
  .gplot.grown{outline:2px solid var(--moss);}
  .gplot.grown .gp-status{font-size:0.64rem;font-weight:700;color:var(--moss);}
  .shop-item{display:flex;align-items:center;gap:12px;background:var(--panel-2);border-radius:12px;
    padding:11px 13px;margin-bottom:8px;}
  .shop-item .si-emoji{font-size:1.5rem;}
  .shop-item .si-body{flex:1;}
  .shop-item .si-name{font-weight:700;font-size:0.85rem;}
  .shop-item .si-desc{font-size:0.7rem;color:var(--ink-soft);}
  .shop-item .si-btn{border:none;border-radius:9px;padding:8px 12px;font-size:0.74rem;font-weight:700;
    background:var(--gold);color:var(--gold-ink);white-space:nowrap;}
  .shop-item .si-btn:disabled{background:var(--line);color:var(--ink-soft);}
  .shop-item .si-btn.owned{background:var(--same);color:var(--moss);}

  /* Themes page */
  .theme-sub-label{font-size:0.78rem;color:var(--ink-soft);margin:16px 0 10px;}
  .theme-grid-full{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;}
  .theme-card{background:var(--panel-2);border-radius:14px;padding:12px;text-align:center;}
  .theme-card .tc-preview{width:100%;aspect-ratio:16/9;border-radius:10px;margin-bottom:8px;position:relative;overflow:hidden;}
  .theme-card .tc-name{font-weight:700;font-size:0.82rem;}
  .theme-card .tc-tag{font-size:0.62rem;color:var(--ink-soft);margin-bottom:8px;}
  .theme-card .tc-btn{width:100%;border:none;border-radius:8px;padding:8px;font-size:0.74rem;font-weight:700;
    background:var(--gold);color:var(--gold-ink);}
  .theme-card .tc-btn:disabled{background:var(--line);color:var(--ink-soft);}
  .theme-card .tc-btn.owned{background:var(--same);color:var(--moss);}
  .theme-card.active{outline:2px solid var(--gold);}
  .design-badge{position:absolute;top:6px;right:6px;background:rgba(0,0,0,0.35);color:#fff;font-size:0.58rem;
    font-weight:700;padding:2px 7px;border-radius:8px;}
  .chest-tier-row{display:flex;align-items:center;gap:12px;background:var(--panel-2);border-radius:12px;
    padding:14px;margin-bottom:10px;}
  .chest-tier-row .ct-emoji{font-size:2rem;}
  .chest-open-btn{width:100%;background:var(--gold);color:var(--gold-ink);border:none;border-radius:12px;
    padding:14px;font-weight:800;font-size:0.95rem;margin-top:6px;}
  .chest-open-btn:disabled{background:var(--panel-2);color:var(--ink-soft);}

  .win-card{background:var(--panel);border-radius:20px;padding:28px 24px;text-align:center;max-width:340px;width:100%;}
  .win-card .trophy{font-size:3rem;}
  .win-card h2{margin:8px 0 4px;font-size:1.3rem;}
  .win-card p{color:var(--ink-soft);margin:0 0 16px;font-size:0.86rem;}
  .win-stats{display:flex;justify-content:space-around;margin-bottom:14px;}
  .win-stats div .v{font-weight:800;font-size:1.05rem;}
  .win-stats div .l{font-size:0.58rem;color:var(--ink-soft);text-transform:uppercase;font-weight:600;}
  .win-rewards{display:flex;justify-content:center;gap:14px;margin-bottom:16px;font-weight:700;font-size:0.9rem;}
  .win-rewards .wr{background:var(--panel-2);border-radius:10px;padding:8px 14px;}
  .win-card button.win-btn{width:100%;border:none;border-radius:12px;padding:14px;font-weight:800;
    background:var(--bg-deep);color:var(--ink-on-deep);font-size:0.96rem;}

  .toast{position:fixed;bottom:24px;left:50%;transform:translateX(-50%);background:var(--bg-deep);
    color:var(--ink-on-deep);padding:10px 18px;border-radius:11px;font-size:0.82rem;font-weight:600;z-index:60;
    opacity:0;transition:opacity .3s, transform .3s;pointer-events:none;max-width:88%;text-align:center;}
  .toast.show{opacity:1;transform:translateX(-50%) translateY(-4px);}
  .pausebox{position:absolute;inset:8px;background:var(--panel);border-radius:12px;display:none;
    align-items:center;justify-content:center;flex-direction:column;gap:14px;z-index:5;}
  .pausebox.show{display:flex;}
  .pausebox button{background:var(--bg-deep);color:var(--ink-on-deep);border:none;border-radius:11px;
    padding:12px 24px;font-weight:700;}
</style>
</head>
<body>
<div class="app">

  <button class="drawer-toggle" id="drawerToggle" aria-label="Menu"><span></span></button>
  <div class="drawer-backdrop" id="drawerBackdrop"></div>
  <div class="drawer" id="drawer">
    <button class="close-drawer" id="closeDrawer">✕</button>
    <h3 style="margin-top:0;">Appearance</h3>
    <div class="toggle-switch">
      <button id="dayModeBtn" class="active">☀️ Day</button>
      <button id="nightModeBtn">🌙 Night</button>
    </div>
    <h3>Color Theme</h3>
    <div class="color-swatch-row" id="colorThemeRow"></div>
    <button class="drawer-btn" id="browseThemesBtn">🎨 Browse All Themes</button>
    <h3>Sound</h3>
    <div class="toggle-switch">
      <button id="soundOnBtn" class="active">🔊 Effects On</button>
      <button id="soundOffBtn">🔇 Off</button>
    </div>
    <div class="toggle-switch">
      <button id="musicOnBtn" class="active">🎵 Music On</button>
      <button id="musicOffBtn">🎵 Off</button>
    </div>
    <h3>Your Companion</h3>
    <div class="companion-card">
      <div class="companion-emoji" id="drawerCompanionEmoji">🌱</div>
      <div class="companion-stage" id="drawerCompanionStage">Seed</div>
      <div class="companion-sub" id="drawerCompanionSub">Play daily to help it grow</div>
    </div>
    <h3>Progress</h3>
    <div class="drawer-row"><span>Current level</span><span class="v" id="dLevel">1</span></div>
    <div class="drawer-row"><span>Games won</span><span class="v" id="dGamesWon">0</span></div>
    <div class="drawer-row"><span>Badges earned</span><span class="v" id="dBadges">0 / 10</span></div>
    <button class="drawer-btn" id="drawerRewardsBtn">🎁 Reward Center</button>
    <button class="drawer-btn" id="drawerStatsBtn">Full statistics</button>
    <button class="drawer-btn" id="drawerBadgesBtn">View all badges</button>
    <h3>What makes this different</h3>
    <div class="usp-item"><span class="uicon">🧭</span><span>Logic Coach explains <i>why</i> a number belongs, teaching technique.</span></div>
    <div class="usp-item"><span class="uicon">🌳</span><span>A companion that grows with your daily streak.</span></div>
    <div class="usp-item"><span class="uicon">🎁</span><span>Coins, seeds, a growing garden and reward chests.</span></div>
  </div>

  <!-- ================= HOME ================= -->
  <div id="homeScreen">
    <div class="hero" id="heroBand">
      <div class="coin-strip">
        <span class="coin-pill"><svg class="pill-ico" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9" fill="#f2c94c" stroke="#d9a520" stroke-width="1.5"/><circle cx="12" cy="12" r="5.5" fill="none" stroke="#d9a520" stroke-width="1.3"/></svg><span id="heroCoins">0</span></span>
        <span class="coin-pill"><svg class="pill-ico" viewBox="0 0 24 24" aria-hidden="true"><ellipse cx="12" cy="13" rx="6" ry="8" fill="#8a5a2b"/><path d="M12 5 Q13 9 12 13" fill="none" stroke="#5e3a17" stroke-width="1.2"/><path d="M9 6 Q12 3 15 6" fill="#6fae6f" stroke="#4a824a" stroke-width="1"/></svg><span id="heroSeeds">0</span></span>
      </div>
      <h1>Sudokuza</h1>
      <p class="tag">A puzzle that grows with you.</p>
    </div>

    <!-- LEVEL up top -->
    <div class="level-card">
      <div class="lc-head">
        <span class="lc-region" id="homeRegion">Seedling Patch</span>
        <span class="lc-num" id="homeLevelNum">Level 1</span>
      </div>
      <div class="lc-sub" id="homeRegionSub">Easy · relaxed pace</div>
      <div class="level-strip" id="levelStrip"></div>
      <button class="cta-btn" id="continueBtn">Continue Journey</button>
    </div>

    <!-- DIFFICULTY picker on home -->
    <div class="section">
      <div class="section-label">Practice a Difficulty</div>
      <div class="diff-grid" id="homeDiffGrid">
        <button class="diff-tile d-easy" data-hdiff="0"><span class="dt-name">Easy</span><span class="dt-sub">Seedling Patch</span></button>
        <button class="diff-tile d-medium" data-hdiff="1"><span class="dt-name">Medium</span><span class="dt-sub">Greenhouse</span></button>
        <button class="diff-tile d-hard" data-hdiff="2"><span class="dt-name">Hard</span><span class="dt-sub">Wildwood</span></button>
        <button class="diff-tile d-expert" data-hdiff="3"><span class="dt-name">Expert</span><span class="dt-sub">Ancient Canopy</span></button>
      </div>
    </div>

    <!-- DAILY below -->
    <div class="section">
      <div class="section-label">Today's Specimen</div>
      <div class="daily-card">
        <div class="dtitle">🌾 One puzzle, shared by everyone</div>
        <div class="dsub" id="dailySub">Solve it and compare against your own history.</div>
        <button class="daily-btn" id="dailyPlayBtn">Play today's puzzle</button>
        <div class="daily-done hidden" id="dailyDoneMsg"></div>
      </div>
    </div>

    <!-- REWARDS preview -->
    <div class="section">
      <div class="section-label">Rewards</div>
      <div class="reward-preview">
        <div class="rp-top">
          <span class="rp-title">🎁 Reward Center</span>
          <button class="rp-open" id="openRewardsBtn">Open</button>
        </div>
        <div class="chest-bar-wrap">
          <div class="chest-bar-label"><span>Next chest</span><span id="chestBarText">0 / 8</span></div>
          <div class="chest-bar"><div class="fill" id="chestBarFill" style="width:0%"></div></div>
        </div>
        <div class="garden-mini" id="gardenMini"></div>
      </div>
    </div>

    <div class="section">
      <div class="usp-strip">
        <div class="usp-mini"><span class="mi">🧭</span><span class="mt"><b>Logic Coach</b> gives hints that teach the technique, not just the answer.</span></div>
        <div class="usp-mini"><span class="mi">🌳</span><span class="mt"><b>Living streak</b>: your companion grows every consecutive day.</span></div>
        <div class="usp-mini"><span class="mi">🎁</span><span class="mt"><b>Real rewards</b>: every win earns coins &amp; seeds toward a garden you build.</span></div>
      </div>
    </div>
  </div>

  <!-- ================= GAME ================= -->
  <div id="gameScreen" class="hidden">
    <div class="gtopbar" id="gtopbar">
      <button class="icon-btn" id="backHomeBtn">←</button>
      <div class="region-tag" id="regionTag">Seedling Patch · Level 1</div>
      <button class="icon-btn" id="pauseBtn">⏸</button>
    </div>
    <div class="statrow">
      <div class="stat"><div class="label">Mistakes</div><div class="value" id="mistakesVal">0/3</div></div>
      <div class="stat"><div class="label">Score</div><div class="value" id="scoreVal">0</div></div>
      <div class="stat"><div class="label">Time</div><div class="value" id="timerVal">00:00</div></div>
    </div>
    <div class="board-shell">
      <div class="board" id="board"></div>
      <div class="pausebox" id="pausebox">
        <div style="font-weight:800;font-size:1.1rem;font-family:var(--display);">Paused</div>
        <button id="resumeBtn">Resume</button>
      </div>
    </div>
    <div class="coach-panel" id="coachPanel"><span class="ci">🧭</span><span id="coachText"></span></div>
    <div class="toolbar">
      <button class="tool" id="undoTool"><span class="ticon">↺</span>Undo</button>
      <button class="tool" id="eraseTool"><span class="ticon">⌫</span>Erase</button>
      <button class="tool" id="notesTool"><span class="ticon">✎</span>Notes</button>
      <button class="tool" id="coachTool"><span class="ticon">🧭</span>Coach<span class="badge" id="coachBadge">3</span></button>
    </div>
    <div class="numpad" id="numpad"></div>
  </div>
</div>

<!-- Stats modal -->
<div class="overlay" id="statsOverlay">
  <div class="modal">
    <button class="modal-close" id="closeStats">✕</button>
    <h2>Statistics</h2><p class="sub">Your progress so far</p>
    <div class="stat-row"><span class="srlabel">🏆 Games Won</span><span class="srvalue" id="sGamesWon">0</span></div>
    <div class="stat-row"><span class="srlabel">⭐ Best Score</span><span class="srvalue" id="sBestScore">0</span></div>
    <div class="stat-row"><span class="srlabel">🚩 Wins with No Mistakes</span><span class="srvalue" id="sNoMistakeWins">0</span></div>
    <div class="stat-row"><span class="srlabel">⏱ Best Time</span><span class="srvalue" id="sBestTime">--:--</span></div>
    <div class="stat-row"><span class="srlabel">🕐 Average Time</span><span class="srvalue" id="sAvgTime">--:--</span></div>
    <div class="stat-row"><span class="srlabel">📈 Current Level</span><span class="srvalue" id="sLevel">1</span></div>
    <div class="stat-row"><span class="srlabel">🔥 Longest Streak</span><span class="srvalue" id="sLongestStreak">0</span></div>
    <div class="stat-row"><span class="srlabel">📅 Daily Puzzles Done</span><span class="srvalue" id="sDailyDone">0</span></div>
  </div>
</div>

<!-- Badges modal -->
<div class="overlay" id="badgesOverlay">
  <div class="modal">
    <button class="modal-close" id="closeBadges">✕</button>
    <h2>Badges</h2><p class="sub" id="badgeProgress">0 of 10 earned</p>
    <div class="badge-grid" id="badgeGrid"></div>
  </div>
</div>

<!-- Themes page -->
<div class="overlay" id="themesOverlay">
  <div class="modal">
    <button class="modal-close" id="closeThemes">✕</button>
    <h2>Themes</h2>
    <p class="sub" id="themesCoinsLine">You have 0 coins. Clear levels to earn more.</p>
    <div class="theme-sub-label">Color Themes</div>
    <div class="theme-grid-full" id="colorThemesGrid"></div>
    <div class="theme-sub-label">Design Themes, color plus a background pattern</div>
    <div class="theme-grid-full" id="designThemesGrid"></div>
  </div>
</div>

<!-- Reward Center modal -->
<div class="overlay" id="rewardsOverlay">
  <div class="modal">
    <button class="modal-close" id="closeRewards">✕</button>
    <h2>Reward Center</h2>
    <div class="rc-balance">
      <div class="bpill"><div class="bv" id="rcCoins">0</div><div class="bl">🪙 Coins</div></div>
      <div class="bpill"><div class="bv" id="rcSeeds">0</div><div class="bl">🌰 Seeds</div></div>
      <div class="bpill"><div class="bv" id="rcChests">0</div><div class="bl">📦 Chests</div></div>
    </div>
    <div class="rc-tabs">
      <button data-tab="garden" class="active">Garden</button>
      <button data-tab="shop">Shop</button>
      <button data-tab="chests">Chests</button>
    </div>
    <div id="rcGardenTab">
      <p class="sub">Spend 🌰 seeds to grow your grove. Each plot stays forever.</p>
      <div class="garden-full" id="gardenFull"></div>
    </div>
    <div id="rcShopTab" class="hidden">
      <p class="sub">Spend 🪙 coins on themes, companion skins, and power-ups.</p>
      <div id="shopList"></div>
    </div>
    <div id="rcChestsTab" class="hidden">
      <p class="sub">Fill the bar by winning. Every 8 points earns a chest.</p>
      <div class="chest-bar-wrap">
        <div class="chest-bar-label"><span>Progress to next chest</span><span id="rcChestBarText">0 / 8</span></div>
        <div class="chest-bar"><div class="fill" id="rcChestBarFill" style="width:0%"></div></div>
      </div>
      <div class="chest-tier-row">
        <span class="ct-emoji">📦</span>
        <div><div style="font-weight:700;font-size:0.9rem;">Unopened chests: <span id="rcChestCount">0</span></div>
        <div style="font-size:0.72rem;color:var(--ink-soft);">Each chest gives coins + seeds, and sometimes a rare bonus.</div></div>
      </div>
      <button class="chest-open-btn" id="openChestBtn" disabled>Open a chest</button>
    </div>
  </div>
</div>

<!-- Win overlay -->
<div class="overlay" id="winOverlay">
  <div class="win-card" id="winCard">
    <div class="trophy" id="winIcon">🏆</div>
    <h2 id="winTitle">Level Solved!</h2>
    <p id="winSub">Great work. On to the next challenge.</p>
    <div class="win-stats">
      <div><div class="v" id="winTime">00:00</div><div class="l">Time</div></div>
      <div><div class="v" id="winScore">0</div><div class="l">Score</div></div>
      <div><div class="v" id="winMistakes">0</div><div class="l">Mistakes</div></div>
    </div>
    <div class="win-rewards" id="winRewards"></div>
    <button class="win-btn" id="winContinueBtn">Continue</button>
  </div>
</div>

<div class="toast" id="toast"></div>

<script>
(function(){
"use strict";

/* ========== Persistence ========== */
function lsGet(key, fallback){ try{ const v=localStorage.getItem(key); return v===null?fallback:JSON.parse(v);}catch(e){return fallback;} }
function lsSet(key, val){ try{ localStorage.setItem(key, JSON.stringify(val)); }catch(e){} }

/* ========== Audio engine (synthesized, no external files) ========== */
const Audio2 = (function(){
  let ctx=null, masterGain=null, musicGain=null, sfxGain=null;
  let soundOn = lsGet("sg_soundOn", true);
  let musicOn = lsGet("sg_musicOn", true);
  let musicTimer=null, musicStarted=false;

  function ensure(){
    if(ctx) return;
    try{
      const AC = window.AudioContext || window.webkitAudioContext;
      if(!AC) return;
      ctx = new AC();
      masterGain = ctx.createGain(); masterGain.gain.value = 0.9; masterGain.connect(ctx.destination);
      musicGain = ctx.createGain(); musicGain.gain.value = musicOn?0.18:0; musicGain.connect(masterGain);
      sfxGain = ctx.createGain(); sfxGain.gain.value = soundOn?0.5:0; sfxGain.connect(masterGain);
    }catch(e){ ctx=null; }
  }
  function resume(){ if(ctx && ctx.state==='suspended') ctx.resume(); }

  // one-shot tone
  function tone(freq, dur, type, when, vol){
    if(!ctx) return;
    const t0 = (when||ctx.currentTime);
    const osc = ctx.createOscillator();
    const g = ctx.createGain();
    osc.type = type||'sine';
    osc.frequency.setValueAtTime(freq, t0);
    g.gain.setValueAtTime(0.0001, t0);
    g.gain.exponentialRampToValueAtTime(vol||0.4, t0+0.012);
    g.gain.exponentialRampToValueAtTime(0.0001, t0+dur);
    osc.connect(g); g.connect(sfxGain);
    osc.start(t0); osc.stop(t0+dur+0.02);
  }

  const SFX = {
    place(){ ensure();resume(); tone(523.25,0.10,'sine'); },                 // C5 soft click
    wrong(){ ensure();resume(); tone(180,0.18,'sawtooth',0,0.3); tone(140,0.22,'sawtooth',ctx?ctx.currentTime+0.06:0,0.25); },
    erase(){ ensure();resume(); tone(330,0.08,'triangle'); },
    select(){ ensure();resume(); tone(660,0.05,'sine',0,0.18); },
    coach(){ ensure();resume(); tone(784,0.10,'triangle'); tone(988,0.12,'triangle',ctx?ctx.currentTime+0.08:0); },
    heal(){ ensure();resume(); tone(659,0.10,'sine'); tone(880,0.14,'sine',ctx?ctx.currentTime+0.09:0); },
    win(){ ensure();resume(); if(!ctx)return; const base=ctx.currentTime; [523.25,659.25,783.99,1046.5].forEach((f,i)=>tone(f,0.30,'triangle',base+i*0.12,0.4)); },
    lose(){ ensure();resume(); if(!ctx)return; const base=ctx.currentTime; [440,392,349.23,293.66].forEach((f,i)=>tone(f,0.30,'sawtooth',base+i*0.13,0.3)); },
    reward(){ ensure();resume(); tone(880,0.10,'square',0,0.25); tone(1174,0.12,'square',ctx?ctx.currentTime+0.09:0,0.22); },
    chest(){ ensure();resume(); if(!ctx)return; const base=ctx.currentTime; [659,880,1046,1318].forEach((f,i)=>tone(f,0.18,'triangle',base+i*0.08,0.3)); }
  };

  // Gentle ambient loop: a slow pentatonic arpeggio with soft pad
  const SCALE = [261.63,293.66,329.63,392.00,440.00,523.25,587.33]; // C major pentatonic-ish
  let step=0;
  function musicTick(){
    if(!ctx || !musicOn) return;
    const now = ctx.currentTime;
    // soft plucked note
    const idx = [0,2,4,3,5,4,2,1][step % 8];
    const freq = SCALE[idx];
    const osc = ctx.createOscillator();
    const g = ctx.createGain();
    osc.type='sine';
    osc.frequency.setValueAtTime(freq, now);
    g.gain.setValueAtTime(0.0001, now);
    g.gain.exponentialRampToValueAtTime(0.5, now+0.05);
    g.gain.exponentialRampToValueAtTime(0.0001, now+1.4);
    osc.connect(g); g.connect(musicGain);
    osc.start(now); osc.stop(now+1.5);
    // occasional low pad note
    if(step % 4 === 0){
      const pad = ctx.createOscillator(); const pg = ctx.createGain();
      pad.type='triangle'; pad.frequency.setValueAtTime(freq/2, now);
      pg.gain.setValueAtTime(0.0001, now);
      pg.gain.exponentialRampToValueAtTime(0.3, now+0.3);
      pg.gain.exponentialRampToValueAtTime(0.0001, now+2.4);
      pad.connect(pg); pg.connect(musicGain);
      pad.start(now); pad.stop(now+2.6);
    }
    step++;
  }
  function startMusic(){
    ensure();resume();
    if(!ctx || musicStarted) return;
    musicStarted = true;
    musicTick();
    musicTimer = setInterval(musicTick, 750);
  }
  function setSound(on){ soundOn=on; lsSet("sg_soundOn",on); if(sfxGain) sfxGain.gain.value = on?0.5:0; }
  function setMusic(on){
    musicOn=on; lsSet("sg_musicOn",on);
    if(musicGain) musicGain.gain.value = on?0.18:0;
    if(on) startMusic();
  }
  function isSoundOn(){ return soundOn; }
  function isMusicOn(){ return musicOn; }

  return { play:(name)=>{ if(soundOn && SFX[name]) SFX[name](); }, startMusic, setSound, setMusic, isSoundOn, isMusicOn, resume:()=>{ensure();resume();} };
})();


/* ========== Seeded RNG ========== */
function mulberry32(a){ return function(){ a|=0;a=(a+0x6D2B79F5)|0;let t=Math.imul(a^(a>>>15),1|a);t=(t+Math.imul(t^(t>>>7),61|t))^t;return((t^(t>>>14))>>>0)/4294967296; }; }
function shuffle(arr,rng){ for(let i=arr.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));const t=arr[i];arr[i]=arr[j];arr[j]=t;} return arr; }
function seedFor(playerSeed,level){ let h=(playerSeed^(level*2654435761))>>>0;h=Math.imul(h^(h>>>16),2246822507);h=Math.imul(h^(h>>>13),3266489909);h=(h^(h>>>16))>>>0;return h; }
function hashStr(str){ let h=2166136261>>>0;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0; }

/* ========== Generator ========== */
function boxIndex(r,c){ return Math.floor(r/3)*3+Math.floor(c/3); }
function makeSolvedGrid(rng){
  const grid=Array.from({length:9},()=>Array(9).fill(0));
  const rows=Array(9).fill(0),cols=Array(9).fill(0),boxes=Array(9).fill(0);
  function fill(pos){
    if(pos===81)return true;
    const r=Math.floor(pos/9),c=pos%9,b=boxIndex(r,c);
    const nums=shuffle([1,2,3,4,5,6,7,8,9],rng);
    for(const n of nums){ const bt=1<<(n-1);
      if(!(rows[r]&bt)&&!(cols[c]&bt)&&!(boxes[b]&bt)){
        grid[r][c]=n;rows[r]|=bt;cols[c]|=bt;boxes[b]|=bt;
        if(fill(pos+1))return true;
        grid[r][c]=0;rows[r]&=~bt;cols[c]&=~bt;boxes[b]&=~bt;
      } }
    return false;
  }
  fill(0);return grid;
}
function countSolutions(grid,limit){
  const rows=Array(9).fill(0),cols=Array(9).fill(0),boxes=Array(9).fill(0);const cells=[];
  for(let r=0;r<9;r++)for(let c=0;c<9;c++){const v=grid[r][c];
    if(v!==0){const bt=1<<(v-1);rows[r]|=bt;cols[c]|=bt;boxes[boxIndex(r,c)]|=bt;}else cells.push([r,c]);}
  let count=0;
  function solve(idx){
    if(count>=limit)return;
    if(idx===cells.length){count++;return;}
    const [r,c]=cells[idx],b=boxIndex(r,c);const used=rows[r]|cols[c]|boxes[b];
    for(let n=1;n<=9;n++){const bt=1<<(n-1);
      if(!(used&bt)){rows[r]|=bt;cols[c]|=bt;boxes[b]|=bt;solve(idx+1);rows[r]&=~bt;cols[c]&=~bt;boxes[b]&=~bt;if(count>=limit)return;}}}
  solve(0);return count;
}
function makePuzzle(rng,targetClues){
  const solved=makeSolvedGrid(rng);const puzzle=solved.map(r=>r.slice());const positions=[];
  for(let r=0;r<9;r++)for(let c=0;c<9;c++)positions.push([r,c]);shuffle(positions,rng);
  let clues=81;
  for(const [r,c] of positions){ if(clues<=targetClues)break;const backup=puzzle[r][c];if(backup===0)continue;
    puzzle[r][c]=0;if(countSolutions(puzzle,2)!==1){puzzle[r][c]=backup;}else{clues--;}}
  return {puzzle,solved,clues};
}

/* ========== Difficulty / region ========== */
const DIFF_NAMES=["Easy","Medium","Hard","Expert"];
const REGION_NAMES=["Seedling Patch","Greenhouse","Wildwood","Ancient Canopy"];
const REGION_SUBS=["Easy · relaxed pace","Medium · balanced challenge","Hard · sharp focus","Expert · for masters"];
const DIFF_BASE_CLUES=[38,30,26,22];
const CYCLE_SUFFIX=["","II","III","IV","V","VI","VII","VIII","IX","X"];
function difficultyForLevel(l){ return Math.floor((l-1)/250)%4; }
function cycleForLevel(l){ return Math.floor((l-1)/1000); }
function cluesForLevel(l){ return Math.max(20, DIFF_BASE_CLUES[difficultyForLevel(l)] - cycleForLevel(l)); }
function regionNameForLevel(l){ const cy=cycleForLevel(l);return REGION_NAMES[difficultyForLevel(l)]+(cy>0?(' '+(CYCLE_SUFFIX[cy]||('x'+(cy+1)))):''); }

/* ========== Logic Coach ========== */
function candidatesFor(board,r,c){
  if(board[r][c]!==0)return[];
  const used=new Set();
  for(let i=0;i<9;i++){ if(board[r][i])used.add(board[r][i]); if(board[i][c])used.add(board[i][c]); }
  const br=Math.floor(r/3)*3,bc=Math.floor(c/3)*3;
  for(let rr=br;rr<br+3;rr++)for(let cc=bc;cc<bc+3;cc++)if(board[rr][cc])used.add(board[rr][cc]);
  const cands=[];for(let n=1;n<=9;n++)if(!used.has(n))cands.push(n);return cands;
}
function unitCells(kind,r,c){
  if(kind==='row'){const a=[];for(let cc=0;cc<9;cc++)a.push([r,cc]);return a;}
  if(kind==='col'){const a=[];for(let rr=0;rr<9;rr++)a.push([rr,c]);return a;}
  const a=[];const br=Math.floor(r/3)*3,bc=Math.floor(c/3)*3;for(let rr=br;rr<br+3;rr++)for(let cc=bc;cc<bc+3;cc++)a.push([rr,cc]);return a;
}
function explainCell(board,r,c){
  const cands=candidatesFor(board,r,c);
  if(cands.length===0)return{type:'error',value:null,msg:'This cell has no valid candidates left, so a mistake exists elsewhere on the board.'};
  if(cands.length===1)return{type:'naked_single',value:cands[0],msg:'Every other digit already appears in this row, column, or box, so only '+cands[0]+' is left.'};
  for(const kind of ['box','row','col']){
    const cells=unitCells(kind,r,c);
    for(const cand of cands){
      let onlyHere=true;
      for(const [rr,cc] of cells){ if(rr===r&&cc===c)continue; if(board[rr][cc]!==0)continue;
        if(candidatesFor(board,rr,cc).includes(cand)){onlyHere=false;break;} }
      if(onlyHere){ const kn=kind==='box'?'3x3 box':kind;
        return{type:'hidden_single',value:cand,msg:'In this '+kn+', '+cand+' can only go in this cell. Every other empty cell rules it out.'}; }
    }
  }
  return{type:'advanced',value:null,msg:'This one needs a more advanced technique, so here is the answer this time.'};
}

/* ========== Badges ========== */
const BADGES=[
  {id:"first_win",icon:"🥇",name:"First Win",cond:s=>s.gamesWon>=1},
  {id:"perfectionist",icon:"💎",name:"Flawless",cond:s=>s.winsNoMistakes>=1},
  {id:"speedster",icon:"⚡",name:"Speedster",cond:s=>s.bestTimeSec!==null&&s.bestTimeSec<=180},
  {id:"dedicated",icon:"🔥",name:"Dedicated (10)",cond:s=>s.gamesWon>=10},
  {id:"half_century",icon:"🏅",name:"50 Wins",cond:s=>s.gamesWon>=50},
  {id:"century",icon:"💯",name:"Century Club",cond:s=>s.progressLevel>=100},
  {id:"halfway",icon:"🚀",name:"Level 500",cond:s=>s.progressLevel>=500},
  {id:"grandmaster",icon:"👑",name:"Grandmaster",cond:s=>s.progressLevel>=1000},
  {id:"gardener",icon:"🌷",name:"Gardener",cond:s=>s.gardenPlots>=6},
  {id:"green_thumb",icon:"🌳",name:"Ancient Tree",cond:s=>s.longestStreak>=30}
];

/* ========== Streak / companion ========== */
function todayStr(){ return new Date().toISOString().slice(0,10); }
function updateStreakOnPlay(streak){
  const today=todayStr();
  if(streak.lastPlayedStr===today)return streak;
  let count;
  if(!streak.lastPlayedStr)count=1;
  else{ const last=new Date(streak.lastPlayedStr+'T00:00:00Z');const now=new Date(today+'T00:00:00Z');
    const d=Math.round((now-last)/86400000);count=d===1?streak.count+1:1; }
  return {lastPlayedStr:today,count,longest:Math.max(streak.longest||0,count)};
}
function stageForStreak(s){
  if(s>=30)return{name:'Ancient Tree',emoji:'🌳'};
  if(s>=14)return{name:'Young Tree',emoji:'🌲'};
  if(s>=7)return{name:'Sapling',emoji:'🌿'};
  if(s>=3)return{name:'Sprout',emoji:'🌾'};
  return{name:'Seed',emoji:'🌱'};
}

/* ========== Reward economy ========== */
const CHEST_THRESHOLD=8;
const GARDEN_PLOTS=[
  {id:0,name:'Mossbed',cost:15,emoji:'🌱'},{id:1,name:'Fern Corner',cost:30,emoji:'🌿'},
  {id:2,name:'Wildflowers',cost:50,emoji:'🌼'},{id:3,name:'Berry Bush',cost:80,emoji:'🫐'},
  {id:4,name:'Stone Path',cost:115,emoji:'🪨'},{id:5,name:'Lily Pond',cost:160,emoji:'🪷'},
  {id:6,name:'Young Maple',cost:220,emoji:'🍁'},{id:7,name:'Rose Arch',cost:300,emoji:'🌹'},
  {id:8,name:'Butterfly Glade',cost:400,emoji:'🦋'},{id:9,name:'Willow',cost:520,emoji:'🌳'},
  {id:10,name:'Grove Lantern',cost:680,emoji:'🏮'},{id:11,name:'Ancient Oak',cost:900,emoji:'🌲'}
];
const SHOP=[
  {id:'skin_fox',type:'skin',cost:300,emoji:'🦊',name:'Fox companion',desc:'A clever grove fox'},
  {id:'skin_owl',type:'skin',cost:300,emoji:'🦉',name:'Owl companion',desc:'A wise night owl'},
  {id:'skin_deer',type:'skin',cost:450,emoji:'🦌',name:'Deer companion',desc:'A gentle forest deer'},
  {id:'skin_dragon',type:'skin',cost:800,emoji:'🐉',name:'Dragon companion',desc:'A rare grove dragon'},
  {id:'pow_hint3',type:'powerup',cost:50,emoji:'💡',name:'+3 Coach uses',desc:'For your next puzzle',grants:'coach3'},
  {id:'pow_heal1',type:'powerup',cost:90,emoji:'❤️',name:'+1 Mistake room',desc:'Fail at 4 instead of 3',grants:'heal1'},
  {id:'pow_coach2',type:'powerup',cost:60,emoji:'🧭',name:'+2 Coach uses',desc:'For your next puzzle',grants:'coach2'}
];

/* Unified theme catalog: free colors, paid colors (cheap), paid design themes (color + pattern, pricier).
   Only 'forest','slate','plum' are free; everything else must be bought with coins earned by clearing levels.
   Applies in Day mode only. Night mode always stays neutral black regardless of the chosen theme. */
const CATALOG_THEMES=[
  {id:'forest', name:'Forest', kind:'free', cost:0, swatch:'#1e5940', vars:null},
  {id:'slate',  name:'Slate',  kind:'free', cost:0, swatch:'#2c4a63', vars:{'--bg-deep':'#274357','--bg-deep-2':'#1a2f3d','--gold':'#5fa8d3','--moss':'#4a89ab'}},
  {id:'plum',   name:'Plum',   kind:'free', cost:0, swatch:'#5b3566', vars:{'--bg-deep':'#4f2f5c','--bg-deep-2':'#382042','--gold':'#c98ac9','--moss':'#9a5a9a'}},
  {id:'terracotta', name:'Terracotta', kind:'color', cost:150, swatch:'#a4552f', vars:{'--bg-deep':'#7a4429','--bg-deep-2':'#57301c','--gold':'#e08a52','--moss':'#c2703f'}},
  {id:'moss',   name:'Moss',   kind:'color', cost:120, swatch:'#5c6b2e', vars:{'--bg-deep':'#4a5a2a','--bg-deep-2':'#374420','--gold':'#c7b23a','--moss':'#7f9a49'}},
  {id:'midnight_blue', name:'Midnight Blue', kind:'color', cost:200, swatch:'#232c52', vars:{'--bg-deep':'#232c52','--bg-deep-2':'#181f3c','--gold':'#8b9be0','--moss':'#5f6fb0'}},
  {id:'theme_dusk',   name:'Dusk Bloom',   kind:'design', cost:450, pattern:'dots',   swatch:'#4a3b52', vars:{'--bg':'#f3ede8','--bg-deep':'#4a3b52','--bg-deep-2':'#382a44','--gold':'#e0975a','--moss':'#8a6f9e','--same':'#e6dcea','--sel':'#ece0d6','--peer':'#f0e9e4'}},
  {id:'theme_sakura', name:'Sakura Bloom', kind:'design', cost:450, pattern:'petals', swatch:'#7d4756', vars:{'--bg':'#faf0f2','--bg-deep':'#7d4756','--bg-deep-2':'#63343f','--gold':'#e58aa8','--moss':'#c76d94','--same':'#f6dde6','--sel':'#f7e3ea','--peer':'#f6ecef'}},
  {id:'theme_ocean',  name:'Ocean Waves',  kind:'design', cost:550, pattern:'waves',  swatch:'#20495c', vars:{'--bg':'#eaf1f4','--bg-deep':'#20495c','--bg-deep-2':'#153444','--gold':'#4fb0c9','--moss':'#3d8aa8','--same':'#d3e8ef','--sel':'#dcecf0','--peer':'#e7f0f3'}},
  {id:'theme_ember',  name:'Ember Glow',   kind:'design', cost:650, pattern:'sparks', swatch:'#4a2a24', vars:{'--bg':'#f5eee8','--bg-deep':'#4a2a24','--bg-deep-2':'#361c17','--gold':'#e07a3d','--moss':'#c25a3a','--same':'#f0ddd0','--sel':'#f2e2d6','--peer':'#f3ebe4'}}
];
function themeById(id){ return CATALOG_THEMES.find(t=>t.id===id); }
function themeOwned(reward,id){ const t=themeById(id); return !t || t.kind==='free' || reward.ownedThemes.includes(id); }

/* ========== State ========== */
let playerSeed=lsGet("sg_playerSeed",null);
if(playerSeed===null){ playerSeed=Math.floor(Math.random()*4294967295);lsSet("sg_playerSeed",playerSeed); }
let progressLevel=lsGet("sg_progressLevel",1);
let stats=lsGet("sg_stats",{gamesWon:0,bestScore:0,winsNoMistakes:0,bestTimeSec:null,totalTimeSec:0,totalGames:0});
let earnedBadges=lsGet("sg_badges",[]);
let uiMode=lsGet("sg_uiMode","day");
let streak=lsGet("sg_streak",{lastPlayedStr:null,count:0,longest:0});
let dailyHistory=lsGet("sg_dailyHistory",{});
let reward=lsGet("sg_reward",{coins:0,seeds:0,chestPoints:0,chests:0,gardenPlots:[],ownedShop:[],ownedThemes:[],activeTheme:'forest',activeSkin:null});
if(!reward.ownedThemes) reward.ownedThemes=[];
if(!reward.activeTheme) reward.activeTheme='forest';
let pendingPowerup=lsGet("sg_pendingPowerup",null);

let mode="level",practiceDiff=0,activeLevel=1,isReplay=false;
let board,given,solution,notes,selected=null;
let mistakes=0,score=0,coachUses=3,notesMode=false,elapsed=0,timerHandle=null,paused=false,undoStack=[],gameEnded=false;
let mistakeLimit=3;

/* ========== DOM ========== */
const $=id=>document.getElementById(id);
const homeScreen=$('homeScreen'),gameScreen=$('gameScreen'),boardEl=$('board'),numpadEl=$('numpad');
const regionTag=$('regionTag'),mistakesVal=$('mistakesVal'),scoreVal=$('scoreVal'),timerVal=$('timerVal');
const coachBadge=$('coachBadge'),coachPanel=$('coachPanel'),coachText=$('coachText'),toastEl=$('toast'),pauseboxEl=$('pausebox');

const cellEls=[];
for(let r=0;r<9;r++)for(let c=0;c<9;c++){
  const d=document.createElement('div');d.className='cell';
  const tr=(c%3===2&&c!==8),tb=(r%3===2&&r!==8);
  d.style.borderRight=(tr?'2px':'1px')+' solid var(--line'+(tr?'-thick':'')+')';
  d.style.borderBottom=(tb?'2px':'1px')+' solid var(--line'+(tb?'-thick':'')+')';
  d.addEventListener('click',(function(rr,cc){return function(){selectCell(rr,cc);};})(r,c));
  boardEl.appendChild(d);cellEls.push(d);
}
const numBtnEls=[];
for(let n=1;n<=9;n++){ const b=document.createElement('button');b.className='numbtn';b.textContent=n;
  b.addEventListener('click',(function(nn){return function(){inputNumber(nn);};})(n));numpadEl.appendChild(b);numBtnEls.push(b); }

/* ========== Toast ========== */
let toastTimer=null;
function showToast(msg){ toastEl.textContent=msg;toastEl.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toastEl.classList.remove('show'),2400); }

/* ========== Timer ========== */
function startTimer(){ stopTimer();timerHandle=setInterval(()=>{if(!paused&&!gameEnded){elapsed++;renderTimer();}},1000); }
function stopTimer(){ if(timerHandle)clearInterval(timerHandle);timerHandle=null; }
function fmtTime(s){ const m=Math.floor(s/60),ss=s%60;return String(m).padStart(2,'0')+':'+String(ss).padStart(2,'0'); }
function renderTimer(){ timerVal.textContent=fmtTime(elapsed); }

/* ========== Theme ========== */
function applyUiMode(){
  document.documentElement.setAttribute('data-mode',uiMode);
  $('dayModeBtn').classList.toggle('active',uiMode==='day');
  $('nightModeBtn').classList.toggle('active',uiMode==='night');
  const root=document.documentElement;
  ['--bg','--bg-deep','--bg-deep-2','--gold','--moss','--same','--sel','--peer'].forEach(v=>root.style.removeProperty(v));

  const hero=$('heroBand');
  const gtopbar=$('gtopbar');
  let pattern='';
  // Themes only colorize Day mode. Night mode always stays neutral black, regardless of chosen theme.
  if(uiMode==='day'){
    const active=themeById(reward.activeTheme) || themeById('forest');
    if(active && active.vars){
      for(const k in active.vars) root.style.setProperty(k,active.vars[k]);
    }
    if(active && active.kind==='design' && active.pattern) pattern=active.pattern;
  }
  if(hero){ if(pattern) hero.setAttribute('data-pattern',pattern); else hero.removeAttribute('data-pattern'); }
  if(gtopbar){ if(pattern) gtopbar.setAttribute('data-pattern',pattern); else gtopbar.removeAttribute('data-pattern'); }
}
function selectQuickTheme(id){
  const t=themeById(id);
  if(!t) return;
  if(themeOwned(reward,id)){
    reward.activeTheme=id;lsSet("sg_reward",reward);applyUiMode();renderColorThemeRow();
    return;
  }
  // not owned: attempt purchase right from the quick row
  if(reward.coins>=t.cost){
    reward.coins-=t.cost;reward.ownedThemes.push(id);reward.activeTheme=id;lsSet("sg_reward",reward);
    Audio2.play('reward');showToast(t.name+' unlocked for '+t.cost+' coins!');
    applyUiMode();renderColorThemeRow();
  }else{
    showToast('Not enough coins yet. Clear levels to earn more, then come back for '+t.name+'.');
  }
}
function renderColorThemeRow(){
  const row=$('colorThemeRow');row.innerHTML='';
  // 3 free colors, plus one paid quick-pick (terracotta) shown with its price if not owned
  const quickIds=['forest','slate','plum','terracotta'];
  quickIds.forEach(function(id){
    const t=themeById(id);if(!t)return;
    const owned=themeOwned(reward,id);
    const sw=document.createElement('div');
    sw.className='color-swatch'+(reward.activeTheme===id?' selected':'');
    sw.style.background=t.swatch;
    sw.title=owned?t.name:(t.name+', '+t.cost+' coins');
    if(!owned){
      const lock=document.createElement('div');
      lock.style.cssText='position:absolute;inset:0;display:flex;align-items:center;justify-content:center;font-size:0.7rem;color:#fff;text-shadow:0 1px 2px rgba(0,0,0,0.5);';
      lock.textContent='🔒';
      sw.style.position='relative';
      sw.appendChild(lock);
    }
    sw.addEventListener('click',function(){ selectQuickTheme(id); });
    row.appendChild(sw);
  });
}

/* Full Themes page */
function openThemesPage(){
  $('themesCoinsLine').textContent='You have '+reward.coins+' coins. Clear levels to earn more.';
  renderThemeGrid('colorThemesGrid', CATALOG_THEMES.filter(t=>t.kind==='free'||t.kind==='color'));
  renderThemeGrid('designThemesGrid', CATALOG_THEMES.filter(t=>t.kind==='design'));
  openOverlay('themesOverlay');
}
function renderThemeGrid(containerId, list){
  const grid=$(containerId);grid.innerHTML='';
  list.forEach(function(t){
    const owned=themeOwned(reward,t.id);
    const active=reward.activeTheme===t.id;
    const card=document.createElement('div');
    card.className='theme-card'+(active?' active':'');
    const preview=document.createElement('div');
    preview.className='tc-preview';
    preview.style.background=t.vars?('linear-gradient(135deg,'+t.swatch+',#00000030)'):('linear-gradient(135deg,'+t.swatch+',#00000020)');
    if(t.kind==='design'){ const tag=document.createElement('span');tag.className='design-badge';tag.textContent='✨ Design';preview.appendChild(tag); }
    card.appendChild(preview);
    const name=document.createElement('div');name.className='tc-name';name.textContent=t.name;card.appendChild(name);
    const tag2=document.createElement('div');tag2.className='tc-tag';
    tag2.textContent = t.kind==='free' ? 'Free' : (t.kind==='design' ? 'Design theme' : 'Color theme');
    card.appendChild(tag2);
    const btn=document.createElement('button');btn.className='tc-btn';
    if(active){ btn.textContent='✓ Active'; btn.disabled=true; }
    else if(owned){ btn.classList.add('owned'); btn.textContent='Use'; }
    else{ btn.textContent='🪙 '+t.cost; btn.disabled=reward.coins<t.cost; }
    btn.addEventListener('click',function(){
      if(active) return;
      if(owned){ reward.activeTheme=t.id;lsSet("sg_reward",reward);applyUiMode();renderColorThemeRow();openThemesPage(); }
      else if(reward.coins>=t.cost){
        reward.coins-=t.cost;reward.ownedThemes.push(t.id);reward.activeTheme=t.id;lsSet("sg_reward",reward);
        Audio2.play('reward');showToast(t.name+' unlocked!');applyUiMode();renderColorThemeRow();openThemesPage();
      }else{
        showToast('Not enough coins yet for '+t.name+'.');
      }
    });
    card.appendChild(btn);
    grid.appendChild(card);
  });
}
$('browseThemesBtn').addEventListener('click',()=>{ closeDrawerFn(); openThemesPage(); });
$('closeThemes').addEventListener('click',()=>closeOverlay('themesOverlay'));

$('dayModeBtn').addEventListener('click',()=>{uiMode='day';lsSet('sg_uiMode',uiMode);applyUiMode();});
$('nightModeBtn').addEventListener('click',()=>{uiMode='night';lsSet('sg_uiMode',uiMode);applyUiMode();});

function refreshSoundToggleUI(){
  $('soundOnBtn').classList.toggle('active',Audio2.isSoundOn());
  $('soundOffBtn').classList.toggle('active',!Audio2.isSoundOn());
  $('musicOnBtn').classList.toggle('active',Audio2.isMusicOn());
  $('musicOffBtn').classList.toggle('active',!Audio2.isMusicOn());
}
$('soundOnBtn').addEventListener('click',()=>{Audio2.setSound(true);Audio2.play('select');refreshSoundToggleUI();});
$('soundOffBtn').addEventListener('click',()=>{Audio2.setSound(false);refreshSoundToggleUI();});
$('musicOnBtn').addEventListener('click',()=>{Audio2.setMusic(true);refreshSoundToggleUI();});
$('musicOffBtn').addEventListener('click',()=>{Audio2.setMusic(false);refreshSoundToggleUI();});

/* ========== Screens ========== */
function showHome(){ gameScreen.classList.add('hidden');homeScreen.classList.remove('hidden');renderHome(); }
function showGame(){ homeScreen.classList.add('hidden');gameScreen.classList.remove('hidden'); }

/* ========== Drawer ========== */
const drawerEl=$('drawer'),drawerBackdrop=$('drawerBackdrop');
function openDrawer(){
  $('dLevel').textContent=progressLevel;$('dGamesWon').textContent=stats.gamesWon;
  $('dBadges').textContent=earnedBadges.length+' / '+BADGES.length;
  const st=stageForStreak(streak.count);
  $('drawerCompanionEmoji').textContent=reward.activeSkin?skinEmoji(reward.activeSkin):st.emoji;
  $('drawerCompanionStage').textContent=st.name+' · '+streak.count+' day streak';
  $('drawerCompanionSub').textContent=streak.count>0?('Longest streak: '+streak.longest+' days'):'Play today to start growing it';
  refreshSoundToggleUI();
  renderColorThemeRow();
  drawerEl.classList.add('open');drawerBackdrop.classList.add('show');
}
function skinEmoji(id){ const it=SHOP.find(x=>x.id===id);return it?it.emoji:'🌱'; }
function closeDrawerFn(){ drawerEl.classList.remove('open');drawerBackdrop.classList.remove('show'); }
$('drawerToggle').addEventListener('click',openDrawer);
$('closeDrawer').addEventListener('click',closeDrawerFn);
drawerBackdrop.addEventListener('click',closeDrawerFn);
document.querySelectorAll('.drawer-row[data-diff]').forEach(function(el){
  el.addEventListener('click',function(){ const d=parseInt(el.getAttribute('data-diff'),10);closeDrawerFn();loadPuzzle('practice',{diff:d});showGame(); });
});
$('drawerRewardsBtn').addEventListener('click',()=>{closeDrawerFn();openRewards();});
$('drawerStatsBtn').addEventListener('click',()=>{closeDrawerFn();openStats();});
$('drawerBadgesBtn').addEventListener('click',()=>{closeDrawerFn();openBadges();});

/* ========== Home render ========== */
function renderHome(){
  $('heroCoins').textContent=reward.coins;
  $('heroSeeds').textContent=reward.seeds;

  const diff=difficultyForLevel(progressLevel);
  $('homeRegion').textContent=regionNameForLevel(progressLevel);
  $('homeLevelNum').textContent='Level '+progressLevel;
  $('homeRegionSub').textContent=REGION_SUBS[diff];

  // clean level strip: 5 chips centered on current level
  const strip=$('levelStrip');strip.innerHTML='';
  const start=Math.max(1,progressLevel-2);
  for(let i=0;i<5;i++){
    const lvl=start+i;
    const chip=document.createElement('div');
    let cls='lvchip ';
    if(lvl<progressLevel)cls+='done';
    else if(lvl===progressLevel)cls+='active';
    else cls+='locked';
    chip.className=cls;
    chip.innerHTML = lvl<progressLevel ? '✓' : (lvl>progressLevel ? '<span class="lock">🔒</span>' : lvl);
    if(lvl<=progressLevel){ chip.style.cursor='pointer';
      chip.addEventListener('click',function(){loadPuzzle('level',{level:lvl});showGame();}); }
    strip.appendChild(chip);
  }

  // daily
  const today=todayStr(),doneEntry=dailyHistory[today];
  const dailySub=$('dailySub'),dailyBtn=$('dailyPlayBtn'),dailyDoneMsg=$('dailyDoneMsg');
  if(doneEntry){
    dailySub.textContent="You've completed today's puzzle.";
    dailyBtn.classList.add('hidden');dailyDoneMsg.classList.remove('hidden');
    const dates=Object.keys(dailyHistory);
    const avg=dates.reduce((a,d)=>a+dailyHistory[d].timeSec,0)/dates.length;
    const cmp=dates.length>1?(doneEntry.timeSec<=avg?', faster than your average!':', a little slower than your average.'):'';
    dailyDoneMsg.textContent='Solved in '+fmtTime(doneEntry.timeSec)+', '+doneEntry.mistakes+' mistake(s)'+cmp;
  }else{
    dailySub.textContent='Solve it and compare against your own history.';
    dailyBtn.classList.remove('hidden');dailyDoneMsg.classList.add('hidden');
  }

  // reward preview
  $('chestBarText').textContent=reward.chestPoints+' / '+CHEST_THRESHOLD;
  $('chestBarFill').style.width=Math.round(reward.chestPoints/CHEST_THRESHOLD*100)+'%';
  const gm=$('gardenMini');gm.innerHTML='';
  for(let i=0;i<6;i++){
    const plot=GARDEN_PLOTS[i];
    const grown=reward.gardenPlots.includes(plot.id);
    const el=document.createElement('div');
    el.className='plot '+(grown?'grown':'empty');
    el.textContent=grown?plot.emoji:'·';
    gm.appendChild(el);
  }
}
$('continueBtn').addEventListener('click',()=>{loadPuzzle('level',{level:progressLevel});showGame();});
document.querySelectorAll('.diff-tile[data-hdiff]').forEach(function(el){
  el.addEventListener('click',function(){ const d=parseInt(el.getAttribute('data-hdiff'),10);loadPuzzle('practice',{diff:d});showGame(); });
});
$('dailyPlayBtn').addEventListener('click',()=>{loadPuzzle('daily',{});showGame();});
$('openRewardsBtn').addEventListener('click',openRewards);
$('backHomeBtn').addEventListener('click',()=>{stopTimer();showHome();});

/* ========== Load puzzle ========== */
function loadPuzzle(newMode,opts){
  mode=newMode;let clues,diffIdx,seedBase,label;
  if(mode==='level'){
    activeLevel=opts.level;isReplay=activeLevel<progressLevel;
    diffIdx=difficultyForLevel(activeLevel);clues=cluesForLevel(activeLevel);
    seedBase=seedFor(playerSeed,activeLevel);label=regionNameForLevel(activeLevel)+' · Level '+activeLevel;
  }else if(mode==='practice'){
    practiceDiff=opts.diff;diffIdx=practiceDiff;clues=DIFF_BASE_CLUES[diffIdx];
    seedBase=seedFor(playerSeed,5000000+Math.floor(Math.random()*1000000));label='Practice · '+DIFF_NAMES[diffIdx];
  }else{
    diffIdx=1;clues=DIFF_BASE_CLUES[diffIdx];seedBase=hashStr('sg_daily_'+todayStr());label="Today's Specimen · "+todayStr();
  }
  const rng=mulberry32(seedBase);const gen=makePuzzle(rng,clues);
  board=gen.puzzle.map(r=>r.slice());solution=gen.solved;given=gen.puzzle.map(r=>r.map(v=>v!==0));
  notes=Array.from({length:9},()=>Array(9).fill(0));
  selected=null;mistakes=0;score=0;notesMode=false;elapsed=0;gameEnded=false;undoStack=[];
  coachPanel.classList.remove('show');

  // apply pending powerups (consumed for this puzzle)
  coachUses=3;mistakeLimit=3;
  if(pendingPowerup){
    if(pendingPowerup.coach) coachUses+=pendingPowerup.coach;
    if(pendingPowerup.heal) mistakeLimit+=pendingPowerup.heal;
    pendingPowerup=null;lsSet('sg_pendingPowerup',null);
  }

  regionTag.textContent=label;updateNotesToolUI();renderAll();startTimer();saveGameState();
}

/* ========== Save / restore ========== */
function saveGameState(){
  lsSet("sg_saved_game",{mode,activeLevel,practiceDiff,board,given,solution,notes,mistakes,score,coachUses,mistakeLimit,elapsed,isReplay});
  lsSet("sg_progressLevel",progressLevel);
}
function tryRestoreGame(){
  const s=lsGet("sg_saved_game",null);if(!s)return false;
  try{
    mode=s.mode;activeLevel=s.activeLevel;practiceDiff=s.practiceDiff;board=s.board;given=s.given;solution=s.solution;notes=s.notes;
    mistakes=s.mistakes;score=s.score;coachUses=s.coachUses;mistakeLimit=s.mistakeLimit||3;elapsed=s.elapsed;isReplay=!!s.isReplay;
    selected=null;notesMode=false;gameEnded=false;undoStack=[];
    let label;
    if(mode==='level')label=regionNameForLevel(activeLevel)+' · Level '+activeLevel;
    else if(mode==='practice')label='Practice · '+DIFF_NAMES[practiceDiff];
    else label="Today's Specimen · "+todayStr();
    regionTag.textContent=label;updateNotesToolUI();renderAll();startTimer();showGame();return true;
  }catch(e){return false;}
}

/* ========== Selection ========== */
function selectCell(r,c){ if(gameEnded||paused)return;selected={r,c};Audio2.play('select');coachPanel.classList.remove('show');renderBoard(); }
function isPeer(r,c,sr,sc){ return r===sr||c===sc||boxIndex(r,c)===boxIndex(sr,sc); }

/* ========== Render ========== */
function renderBoard(){
  for(let r=0;r<9;r++)for(let c=0;c<9;c++){
    const idx=r*9+c,el=cellEls[idx],v=board[r][c];
    el.innerHTML='';el.className='cell';
    if(!given[r][c]&&v!==0)el.classList.add(v!==solution[r][c]?'error':'entry');
    if(v!==0){el.textContent=v;}
    else{ const nm=notes[r][c];
      if(nm){const nw=document.createElement('div');nw.className='notes';
        for(let n=1;n<=9;n++){const sp=document.createElement('span');if(nm&(1<<(n-1)))sp.textContent=n;nw.appendChild(sp);}el.appendChild(nw);} }
    if(selected){
      if(selected.r===r&&selected.c===c)el.classList.add('selected');
      else if(isPeer(r,c,selected.r,selected.c))el.classList.add('peer');
      const sv=board[selected.r][selected.c];
      if(sv!==0&&v===sv&&!(selected.r===r&&selected.c===c))el.classList.add('same');
    }
  }
  updateNumpadState();
}
function updateNumpadState(){
  const counts=Array(10).fill(0);
  for(let r=0;r<9;r++)for(let c=0;c<9;c++){const v=board[r][c];if(v!==0&&v===solution[r][c])counts[v]++;}
  for(let n=1;n<=9;n++)numBtnEls[n-1].disabled=counts[n]>=9;
}
function renderAll(){
  renderBoard();scoreVal.textContent=score;
  mistakesVal.textContent=mistakes+'/'+mistakeLimit;
  mistakesVal.classList.toggle('danger',mistakes>=mistakeLimit-1);
  coachBadge.textContent=coachUses;renderTimer();
}

/* ========== Gameplay ========== */
function pushUndo(a){ undoStack.push(a); }
function inputNumber(n){
  if(gameEnded||paused||!selected)return;
  const {r,c}=selected;if(given[r][c])return;
  const prevValue=board[r][c],prevNotes=notes[r][c];
  if(notesMode){ notes[r][c]=prevNotes^(1<<(n-1));pushUndo({r,c,prevValue,prevNotes,mistakeAdded:false});renderBoard();saveGameState();return; }
  if(prevValue===n)return;
  board[r][c]=n;notes[r][c]=0;let mistakeAdded=false;
  if(n!==solution[r][c]){ mistakes++;mistakeAdded=true;score=Math.max(0,score-5);Audio2.play('wrong'); }
  else{ score+=10;clearPeerNotes(r,c,n);const healed=checkAutoHeal(r,c);Audio2.play(healed?'heal':'place'); }
  pushUndo({r,c,prevValue,prevNotes,mistakeAdded});renderAll();saveGameState();
  if(mistakes>=mistakeLimit){ endGame(false);return; }
  if(isBoardComplete())endGame(true);
}
function clearPeerNotes(r,c,n){
  const bit=1<<(n-1);
  for(let i=0;i<9;i++){ if(board[r][i]===0)notes[r][i]&=~bit; if(board[i][c]===0)notes[i][c]&=~bit; }
  const br=Math.floor(r/3)*3,bc=Math.floor(c/3)*3;
  for(let rr=br;rr<br+3;rr++)for(let cc=bc;cc<bc+3;cc++)if(board[rr][cc]===0)notes[rr][cc]&=~bit;
}
function checkAutoHeal(r,c){
  if(mistakes<=0)return false;
  if(isUnitCorrect(rowCells(r))||isUnitCorrect(colCells(c))||isUnitCorrect(boxCells(r,c))){
    mistakes=Math.max(0,mistakes-1);showToast("Auto-healed 1 mistake!");return true;
  }
  return false;
}
function rowCells(r){const a=[];for(let c=0;c<9;c++)a.push([r,c]);return a;}
function colCells(c){const a=[];for(let r=0;r<9;r++)a.push([r,c]);return a;}
function boxCells(r,c){const a=[];const br=Math.floor(r/3)*3,bc=Math.floor(c/3)*3;for(let rr=br;rr<br+3;rr++)for(let cc=bc;cc<bc+3;cc++)a.push([rr,cc]);return a;}
function isUnitCorrect(cells){return cells.every(([r,c])=>board[r][c]!==0&&board[r][c]===solution[r][c]);}
function isBoardComplete(){for(let r=0;r<9;r++)for(let c=0;c<9;c++)if(board[r][c]!==solution[r][c])return false;return true;}
function eraseSelected(){
  if(gameEnded||paused||!selected)return;const {r,c}=selected;if(given[r][c])return;
  const prevValue=board[r][c],prevNotes=notes[r][c];if(prevValue===0&&prevNotes===0)return;
  board[r][c]=0;notes[r][c]=0;Audio2.play('erase');pushUndo({r,c,prevValue,prevNotes,mistakeAdded:false});renderAll();saveGameState();
}
function undo(){
  if(gameEnded||paused||undoStack.length===0)return;const a=undoStack.pop();
  board[a.r][a.c]=a.prevValue;notes[a.r][a.c]=a.prevNotes;if(a.mistakeAdded)mistakes=Math.max(0,mistakes-1);renderAll();saveGameState();
}
function cleanBoardForAnalysis(){
  const b=board.map(row=>row.slice());
  for(let r=0;r<9;r++)for(let c=0;c<9;c++)if(b[r][c]!==0&&b[r][c]!==solution[r][c])b[r][c]=0;
  return b;
}
function findBestCoachTarget(cb){
  let fb=null;
  for(let r=0;r<9;r++)for(let c=0;c<9;c++){
    if(given[r][c]||board[r][c]===solution[r][c])continue;
    const ex=explainCell(cb,r,c);
    if(ex.type==='naked_single')return{r,c,ex};
    if(ex.type==='hidden_single'&&!fb)fb={r,c,ex};
    else if(ex.type==='advanced'&&!fb)fb={r,c,ex};
  }
  return fb;
}
function useCoach(){
  if(gameEnded||paused||coachUses<=0)return;
  const cb=cleanBoardForAnalysis();let target;
  if(selected&&!given[selected.r][selected.c]&&board[selected.r][selected.c]!==solution[selected.r][selected.c]){
    target={r:selected.r,c:selected.c,ex:explainCell(cb,selected.r,selected.c)};
  }else{ target=findBestCoachTarget(cb); }
  if(!target)return;
  const {r,c,ex}=target;selected={r,c};coachText.textContent=ex.msg;coachPanel.classList.add('show');Audio2.play('coach');
  const cv=solution[r][c];board[r][c]=cv;notes[r][c]=0;coachUses--;score=Math.max(0,score-15);
  clearPeerNotes(r,c,cv);checkAutoHeal(r,c);renderAll();saveGameState();
  if(isBoardComplete())endGame(true);
}
function toggleNotesMode(){ notesMode=!notesMode;updateNotesToolUI(); }
function updateNotesToolUI(){ $('notesTool').classList.toggle('active',notesMode); }

/* ========== Reward earning ========== */
function coinsForWin(diffIdx,mistakes,elapsed,isReplay){
  if(isReplay)return [8,10,14,18][diffIdx];
  let base=[15,22,32,45][diffIdx];
  if(mistakes===0)base=Math.round(base*1.4);
  return base+Math.max(0,Math.round((300-elapsed)/30));
}
function seedsForWin(diffIdx,mistakes,isReplay){ if(isReplay)return 1;return [2,2,3,4][diffIdx]+(mistakes===0?1:0); }
function chestPointsForWin(mistakes,isDaily){ return 1+(mistakes===0?1:0)+(isDaily?1:0); }

/* ========== End game ========== */
function endGame(won){
  gameEnded=true;stopTimer();
  Audio2.play(won?'win':'lose');
  const wo=$('winOverlay');
  if(won){
    const diffIdx=mode==='level'?difficultyForLevel(activeLevel):(mode==='practice'?practiceDiff:1);
    const mult=[1,1.5,2,2.5][diffIdx];
    score+=Math.round((100+Math.max(0,300-elapsed))*mult);

    stats.gamesWon++;stats.totalGames++;stats.totalTimeSec+=elapsed;
    if(mistakes===0)stats.winsNoMistakes++;
    if(score>stats.bestScore)stats.bestScore=score;
    if(stats.bestTimeSec===null||elapsed<stats.bestTimeSec)stats.bestTimeSec=elapsed;
    lsSet("sg_stats",stats);

    streak=updateStreakOnPlay(streak);lsSet("sg_streak",streak);

    // rewards
    const coinsE=coinsForWin(diffIdx,mistakes,elapsed,isReplay);
    const seedsE=seedsForWin(diffIdx,mistakes,isReplay);
    const chestE=chestPointsForWin(mistakes,mode==='daily');
    reward.coins+=coinsE;reward.seeds+=seedsE;reward.chestPoints+=chestE;
    let chestsGained=0;
    while(reward.chestPoints>=CHEST_THRESHOLD){ reward.chestPoints-=CHEST_THRESHOLD;reward.chests++;chestsGained++; }
    lsSet("sg_reward",reward);

    if(mode==='daily'){ dailyHistory[todayStr()]={timeSec:elapsed,mistakes,score};lsSet("sg_dailyHistory",dailyHistory); }
    if(mode==='level'&&!isReplay){ progressLevel=activeLevel+1;lsSet("sg_progressLevel",progressLevel); }

    $('winIcon').textContent='🏆';
    $('winTitle').textContent=mode==='level'?('Level '+activeLevel+' Solved!'):(mode==='daily'?"Today's Specimen Solved!":'Puzzle Solved!');
    $('winSub').textContent=mistakes===0?'A flawless run. Nice work.':'Great work. On to the next.';
    let rewHtml='<span class="wr">🪙 +'+coinsE+'</span><span class="wr">🌰 +'+seedsE+'</span>';
    if(chestsGained>0)rewHtml+='<span class="wr">📦 +'+chestsGained+'</span>';
    $('winRewards').innerHTML=rewHtml;
    $('winContinueBtn').textContent=mode==='daily'?'Back to Grove':'Continue';
    checkBadges();
    if(chestsGained>0)showToast('📦 You earned '+chestsGained+' chest'+(chestsGained>1?'s':'')+'! Open in Reward Center.');
  }else{
    $('winIcon').textContent='💥';$('winTitle').textContent='Out of Mistakes';
    $('winSub').textContent='This puzzle got the better of you. Try again?';
    $('winRewards').innerHTML='';$('winContinueBtn').textContent='Try Again';
  }
  $('winTime').textContent=fmtTime(elapsed);$('winScore').textContent=score;$('winMistakes').textContent=mistakes;
  wo.classList.add('show');
  $('winContinueBtn').onclick=function(){
    wo.classList.remove('show');
    if(won){
      if(mode==='level')loadPuzzle('level',{level:isReplay?activeLevel:progressLevel});
      else if(mode==='daily'){showHome();return;}
      else loadPuzzle('practice',{diff:practiceDiff});
    }else{
      if(mode==='level')loadPuzzle('level',{level:activeLevel});
      else if(mode==='daily')loadPuzzle('daily',{});
      else loadPuzzle('practice',{diff:practiceDiff});
    }
  };
}

/* ========== Badges ========== */
function checkBadges(){
  const s=Object.assign({},stats,{progressLevel,longestStreak:streak.longest,gardenPlots:reward.gardenPlots.length});
  let earned=[];
  for(const b of BADGES){ if(!earnedBadges.includes(b.id)&&b.cond(s)){earnedBadges.push(b.id);earned.push(b.name);} }
  if(earned.length){ lsSet("sg_badges",earnedBadges);showToast('🏆 Badge earned: '+earned.join(', ')); }
}

/* ========== Modals ========== */
function openOverlay(id){ $(id).classList.add('show'); }
function closeOverlay(id){ $(id).classList.remove('show'); }
function openStats(){
  $('sGamesWon').textContent=stats.gamesWon;$('sBestScore').textContent=stats.bestScore;
  $('sNoMistakeWins').textContent=stats.winsNoMistakes;
  $('sBestTime').textContent=stats.bestTimeSec!==null?fmtTime(stats.bestTimeSec):'--:--';
  $('sAvgTime').textContent=stats.totalGames>0?fmtTime(Math.round(stats.totalTimeSec/stats.totalGames)):'--:--';
  $('sLevel').textContent=progressLevel;$('sLongestStreak').textContent=streak.longest+' days';
  $('sDailyDone').textContent=Object.keys(dailyHistory).length;openOverlay('statsOverlay');
}
$('closeStats').addEventListener('click',()=>closeOverlay('statsOverlay'));
function openBadges(){
  const grid=$('badgeGrid');grid.innerHTML='';let cnt=0;
  const s=Object.assign({},stats,{progressLevel,longestStreak:streak.longest,gardenPlots:reward.gardenPlots.length});
  BADGES.forEach(function(b){ const has=earnedBadges.includes(b.id);if(has)cnt++;
    const it=document.createElement('div');it.className='badge-item'+(has?'':' locked');
    it.innerHTML='<div class="bicon">'+b.icon+'</div><div class="bname">'+b.name+'</div>';grid.appendChild(it); });
  $('badgeProgress').textContent=cnt+' of '+BADGES.length+' earned';openOverlay('badgesOverlay');
}
$('closeBadges').addEventListener('click',()=>closeOverlay('badgesOverlay'));

/* ========== Reward Center ========== */
function openRewards(){ renderRewards();openOverlay('rewardsOverlay'); }
$('closeRewards').addEventListener('click',()=>closeOverlay('rewardsOverlay'));
document.querySelectorAll('.rc-tabs button').forEach(function(btn){
  btn.addEventListener('click',function(){
    document.querySelectorAll('.rc-tabs button').forEach(b=>b.classList.remove('active'));
    btn.classList.add('active');
    const tab=btn.getAttribute('data-tab');
    $('rcGardenTab').classList.toggle('hidden',tab!=='garden');
    $('rcShopTab').classList.toggle('hidden',tab!=='shop');
    $('rcChestsTab').classList.toggle('hidden',tab!=='chests');
  });
});
function renderRewards(){
  $('rcCoins').textContent=reward.coins;$('rcSeeds').textContent=reward.seeds;$('rcChests').textContent=reward.chests;

  // garden
  const gf=$('gardenFull');gf.innerHTML='';
  const nextPlot=GARDEN_PLOTS.find(p=>!reward.gardenPlots.includes(p.id));
  GARDEN_PLOTS.forEach(function(p){
    const grown=reward.gardenPlots.includes(p.id);
    const el=document.createElement('div');el.className='gplot'+(grown?' grown':'');
    let btnHtml;
    if(grown) btnHtml='<div class="gp-status">✓ Grown</div>';
    else if(nextPlot&&nextPlot.id===p.id){
      const can=reward.seeds>=p.cost;
      btnHtml='<button class="gp-btn" '+(can?'':'disabled')+' data-plot="'+p.id+'">🌰 '+p.cost+'</button>';
    }else{
      btnHtml='<button class="gp-btn" disabled>🌰 '+p.cost+'</button>';
    }
    el.innerHTML='<div class="gp-emoji">'+(grown?p.emoji:'·')+'</div><div class="gp-name">'+p.name+'</div>'+btnHtml;
    gf.appendChild(el);
  });
  gf.querySelectorAll('.gp-btn[data-plot]').forEach(function(btn){
    btn.addEventListener('click',function(){ growPlot(parseInt(btn.getAttribute('data-plot'),10)); });
  });

  // shop
  const sl=$('shopList');sl.innerHTML='';
  SHOP.forEach(function(item){
    const owned=item.type!=='powerup'&&reward.ownedShop.includes(item.id);
    const active=(item.type==='theme'&&reward.activeTheme===item.id)||(item.type==='skin'&&reward.activeSkin===item.id);
    const el=document.createElement('div');el.className='shop-item';
    let btn;
    if(owned){ btn='<button class="si-btn owned" data-use="'+item.id+'">'+(active?'✓ Active':'Use')+'</button>'; }
    else{ const can=reward.coins>=item.cost; btn='<button class="si-btn" '+(can?'':'disabled')+' data-buy="'+item.id+'">🪙 '+item.cost+'</button>'; }
    el.innerHTML='<span class="si-emoji">'+item.emoji+'</span><div class="si-body"><div class="si-name">'+item.name+'</div><div class="si-desc">'+item.desc+'</div></div>'+btn;
    sl.appendChild(el);
  });
  sl.querySelectorAll('.si-btn[data-buy]').forEach(b=>b.addEventListener('click',()=>buyShop(b.getAttribute('data-buy'))));
  sl.querySelectorAll('.si-btn[data-use]').forEach(b=>b.addEventListener('click',()=>useShopItem(b.getAttribute('data-use'))));

  // chests
  $('rcChestBarText').textContent=reward.chestPoints+' / '+CHEST_THRESHOLD;
  $('rcChestBarFill').style.width=Math.round(reward.chestPoints/CHEST_THRESHOLD*100)+'%';
  $('rcChestCount').textContent=reward.chests;
  $('openChestBtn').disabled=reward.chests<=0;
}
function growPlot(id){
  const plot=GARDEN_PLOTS.find(p=>p.id===id);if(!plot)return;
  if(reward.gardenPlots.includes(id))return;
  if(reward.seeds<plot.cost){ showToast('Not enough seeds yet.');return; }
  reward.seeds-=plot.cost;reward.gardenPlots.push(id);lsSet("sg_reward",reward);
  Audio2.play('reward');checkBadges();showToast('🌱 '+plot.name+' has grown!');renderRewards();
}
function buyShop(id){
  const item=SHOP.find(x=>x.id===id);if(!item)return;
  if(reward.coins<item.cost){ showToast('Not enough coins yet.');return; }
  reward.coins-=item.cost;
  if(item.type==='powerup'){
    pendingPowerup=pendingPowerup||{coach:0,heal:0};
    if(item.grants==='coach3')pendingPowerup.coach=(pendingPowerup.coach||0)+3;
    if(item.grants==='coach2')pendingPowerup.coach=(pendingPowerup.coach||0)+2;
    if(item.grants==='heal1')pendingPowerup.heal=(pendingPowerup.heal||0)+1;
    lsSet('sg_pendingPowerup',pendingPowerup);
    showToast('Power-up ready for your next puzzle!');
  }else{
    reward.ownedShop.push(id);
    // auto-activate on purchase
    if(item.type==='theme'){ reward.activeTheme=id;applyUiMode(); }
    if(item.type==='skin'){ reward.activeSkin=id; }
    showToast(item.name+' unlocked!');
  }
  lsSet("sg_reward",reward);Audio2.play('reward');renderRewards();
}
function useShopItem(id){
  const item=SHOP.find(x=>x.id===id);if(!item)return;
  if(item.type==='theme'){ reward.activeTheme=(reward.activeTheme===id?null:id);applyUiMode(); }
  if(item.type==='skin'){ reward.activeSkin=(reward.activeSkin===id?null:id); }
  lsSet("sg_reward",reward);renderRewards();
}
$('openChestBtn').addEventListener('click',function(){
  if(reward.chests<=0)return;
  reward.chests--;
  Audio2.play('chest');
  const rc=20+Math.floor(Math.random()*41);
  const rs=4+Math.floor(Math.random()*9);
  reward.coins+=rc;reward.seeds+=rs;
  let msg='📦 Chest: 🪙 +'+rc+', 🌰 +'+rs;
  if(Math.random()<0.15){ const bonus=50;reward.coins+=bonus;msg+=' + 🪙 '+bonus+' bonus!'; }
  lsSet("sg_reward",reward);showToast(msg);renderRewards();
});

/* ========== Tools wiring ========== */
$('undoTool').addEventListener('click',undo);
$('eraseTool').addEventListener('click',eraseSelected);
$('notesTool').addEventListener('click',toggleNotesMode);
$('coachTool').addEventListener('click',useCoach);
$('pauseBtn').addEventListener('click',()=>{paused=true;pauseboxEl.classList.add('show');});
$('resumeBtn').addEventListener('click',()=>{paused=false;pauseboxEl.classList.remove('show');});
document.querySelectorAll('.overlay').forEach(function(ov){
  ov.addEventListener('click',function(e){ if(e.target===ov&&ov.id!=='winOverlay')ov.classList.remove('show'); });
});

/* ========== Keyboard ========== */
window.addEventListener('keydown',function(e){
  if(gameScreen.classList.contains('hidden'))return;
  if(!selected||paused||gameEnded)return;
  if(e.key>='1'&&e.key<='9'){inputNumber(parseInt(e.key,10));return;}
  if(e.key==='Backspace'||e.key==='Delete'||e.key==='0'){eraseSelected();return;}
  const dirs={ArrowUp:[-1,0],ArrowDown:[1,0],ArrowLeft:[0,-1],ArrowRight:[0,1]};
  if(dirs[e.key]){ e.preventDefault();let {r,c}=selected;
    r=Math.min(8,Math.max(0,r+dirs[e.key][0]));c=Math.min(8,Math.max(0,c+dirs[e.key][1]));selectCell(r,c); }
});

/* ========== Boot ========== */
applyUiMode();
if(!tryRestoreGame()){ showHome(); }

// Browsers block audio until the first user gesture. Start music + unlock audio then.
function firstInteraction(){
  Audio2.resume();
  if(Audio2.isMusicOn()) Audio2.startMusic();
  window.removeEventListener('pointerdown', firstInteraction);
  window.removeEventListener('keydown', firstInteraction);
}
window.addEventListener('pointerdown', firstInteraction);
window.addEventListener('keydown', firstInteraction);
})();
</script>
</body>
</html>
`;
