#!/usr/bin/env python3
"""
Regenerates gameHtml.js from the source index.html.

Run this any time you edit www/index.html in the main package and want the
Expo app to pick up the changes:

    python3 generate-game-asset.py

It escapes backslashes, backticks, and template-literal interpolation syntax
(${...}) so the HTML can be safely embedded inside a JS template literal,
regardless of what characters end up in the source file later.
"""
import os

SOURCE = os.path.join(os.path.dirname(__file__), "source-game", "index.html")
OUTPUT = os.path.join(os.path.dirname(__file__), "gameHtml.js")

def main():
    with open(SOURCE, "r", encoding="utf-8") as f:
        html = f.read()

    # Order matters: escape backslashes first, then backticks, then ${
    escaped = html.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")

    js = (
        "// AUTO-GENERATED by generate-game-asset.py. Do not hand-edit.\n"
        "// Regenerate with: python3 generate-game-asset.py\n"
        "export const gameHtml = `" + escaped + "`;\n"
    )

    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write(js)

    print(f"Wrote {OUTPUT} ({len(js)} chars)")

if __name__ == "__main__":
    main()
